---
title: Barrera.dev
baseURL: https://blog.barrera.dev
languageCode: es-ES
copyright: <p>Â© 2026, Ãngel Barrera</p><p><a href="https://github.com/angelbarrera92"><i class="fa-brands fa-github"></i></a></p>|<p><a href="https://x.com/angelbarrera92"><i class="fa-brands fa-x"></i></a></p>|<p><a href="https://www.linkedin.com/in/angelbarrerasanchez/"><i class="fa-brands fa-linkedin"></i></a></p>

theme: hello-friend
defaultContentLanguage: es
pagination:
  pagerSize: 9999 # Let's call it infinite
enableEmoji: true

params:
  rssFullText: true

  rss:
    authorName: Ãngel Barrera
    authorEmail: angelbarrerasanchez+blog@gmail.com

  defaultTheme: light
  showReadingTime: true

languages:
  es:
    title: "Barrera.dev Blog"

    params:
      writtenBy: "Por"
      readMore: "Mas"
      readOtherPosts: "Otros"
      subtitle: "Opiniones, reflexiones y experiencias"
      dateFormatSingle: "02-01-2006"
      dateFormatList: "02-01-2006"
      keywords: "Opiniones,Barrera,Dev,Reflexiones,Experiencias"
      logo:
        logoText: "@ Barrera.dev"

    menu:
      main:
        - identifier: home
          name: "Inicio"
          url: /
          weight: 1
        - identifier: about
          name: "Sobre mi"
          url: /about
          weight: 2
        - identifier: lang
          name: "ğŸ‡ºğŸ‡¸"
          url: /en/
          weight: 3
  en:
    title: "Barrera.dev Blog"

    params:
      writtenBy: "By"
      readMore: "More"
      readOtherPosts: "Others"
      subtitle: "Opinions, reflections and experiences"
      keywords: "Opinions,Barrera,Dev,Reflections,Experiences"
      dateFormatSingle: "02-01-2006"
      dateFormatList: "02-01-2006"
      logo:
        logoText: "@ Barrera.dev"

    menu:
      main:
        - identifier: home
          name: "Home"
          url: /en/
          weight: 1
        - identifier: about
          name: "About me"
          url: /en/about
          weight: 2
        - identifier: lang
          name: "ğŸ‡ªğŸ‡¸"
          url: /
          weight: 3
